spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8802
management:
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'