spring:
  sleuth:
    trace-id128: true
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0                   # 将采样比例设置为1.0，也就是全部都需要。默认是0.1
  zipkin:
    base-url: http://${shitcode.env.zipkin.host}:${shitcode.env.zipkin.port}/     # 指定了 Zipkin 服务器的地址