shitcode:
  env:
    mysql:
      host: localhost
      port: 3306
      username: root
      password: 123456
    redis:
      host: localhost
      port: 6379
    flyway:
      locations: ['filesystem:D:\dev\code\shit-code-cloud-java\biz-template\src\main\resources\tmp_db']