spring:
  rabbitmq:
    addresses: ${shitcode.env.rabbitmq.addresses}
    port: ${shitcode.env.rabbitmq.port}
    username: ${shitcode.env.rabbitmq.username}
    password: ${shitcode.env.rabbitmq.password}