version: '3.7'

services:
  #  rabbit_haproxy:
  #    container_name: rabbit_haproxy
  #    image: ${HAPROXY_IMAGE}
  #    hostname: rabbit_haproxy
  #    networks:
  #      cluster-network:
  #        ipv4_address: ${IP_ADDR_PREFIX}.41
  ##    command: ["/usr/local/etc/redis/redis.conf"]
  #    ports:
  #      - 19188:9188
  #    volumes:
  #      - ${DOCKER_VOLUME}/redis/node1:/usr/local/etc/haproxy/haproxy.cfg
  rabbit_node_1:
    &rabbitmq
    container_name: rabbit_node_1
    image: ${RABBITMQ_IMAGE}
    hostname: rabbit_node_1
    privileged: true
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.41
    extra_hosts:
      - rabbit_node_1:${IP_ADDR_PREFIX}.41
      - rabbit_node_2:${IP_ADDR_PREFIX}.42
      - rabbit_node_3:${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node1:/var/lib/rabbitmq/mnesia
  rabbit_node_2:
    <<: *rabbitmq
    container_name: rabbit_node_2
    hostname: rabbit_node_2
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.42
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node2:/var/lib/rabbitmq/mnesia
  rabbit_node_3:
    <<: *rabbitmq
    container_name: rabbit_node_3
    hostname: rabbit_node_3
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node3:/var/lib/rabbitmq/mnesia
