version: '3.7'

services:
  rabbit_haproxy:
    container_name: rabbit_haproxy
    image: ${HAPROXY_IMAGE}
    hostname: rabbit_haproxy
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.40
    #    command: ["-f","/usr/local/etc/haproxy/haproxy.cfg"]
    ports:
      - 1080:1080
    volumes:
      - ${DOCKER_CONFIG}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  rabbit_node_1:
    &rabbitmq
    container_name: rabbit_node_1
    image: ${RABBITMQ_IMAGE}
    hostname: rabbit_node_1
    privileged: true
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.41
    extra_hosts:
      - rabbit_node_1:${IP_ADDR_PREFIX}.41
      - rabbit_node_2:${IP_ADDR_PREFIX}.42
      - rabbit_node_3:${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node1:/var/lib/rabbitmq/mnesia
  rabbit_node_2:
    depends_on:
      - rabbit_node_1
    <<: *rabbitmq
    container_name: rabbit_node_2
    hostname: rabbit_node_2
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.42
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node2:/var/lib/rabbitmq/mnesia
  rabbit_node_3:
    depends_on:
      - rabbit_node_1
    <<: *rabbitmq
    container_name: rabbit_node_3
    hostname: rabbit_node_3
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node3:/var/lib/rabbitmq/mnesia

  #  rabbitmqctl stop_app
  #  rabbitmqctl reset
  #  rabbitmqctl join_cluster --ram rabbit@rabbit1
  #  rabbitmqctl start_app

  # https://www.cnblogs.com/refuge/p/10359539.html

#  HA sync mode
#manual : 手动模式(默认值) 手动模式下,新加入的节点不会同步老节点的队列(及消息)
#automatic : 自动模式
#
#HA mirror promotion on failure
#  when-synced
#  always (默认值)
#
#HA mirror promotion on shutdown
