shitcode:
  flyway:
    sourceLocation: D:\dev\code\shit-code-cloud-java\service-flyway\src\main\resources\db2\migration
    targetLocation: ${spring.flyway.locations.[0]}
    script-suffix: .sql
    scripts:
      #key需要和文件名一致
      test:
        #name是输出的文件的名字
        name: test
        version: 1
        sharding:
          dbName: aaa
          tableName: bbb
      test2:
        name: test2
        version: 2
      test3:
        name: test3
        startDate: 2020-03-03
        endDate: 2021-03-03
        version: 3
      test4:
        name: test4
        version: 4
        startDate: 2020-03-03
        endDate: 2021-03-03
        sharding:
          type: MULTI_DB_MULTI_TABLE