shitcode:
  flyway:
    sourceLocation: D:\dev\code\shit-code-cloud-java\service-flyway\src\main\resources\db2\migration
    targetLocation: ${spring.flyway.locations.[0]}
    script-suffix: .sql
    scripts:
      test:
        name: test
        version: 1
        dbName: aaa
        tableName: bbb
        sharding:
          type: MULTI_DB_MULTI_TABLE
      test2:
        name: test2
        version: 2
        dbName: aaa
        tableName: bbb
        sharding:
          type: MULTI_DB_MULTI_TABLE